#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DOCKER_ENV_FILE="${DOCKER_ENV_FILE:-$REPO_ROOT/.env}"
DOCKER_COMPOSE_FILE="${DOCKER_COMPOSE_FILE:-$REPO_ROOT/infra/compose/docker-compose-prod.yml}"

SKIP_EMAIL_ALERTS="${SKIP_EMAIL_ALERTS:-1}"
PIPELINE_REPLACE_INPUT_SLICES="${PIPELINE_REPLACE_INPUT_SLICES:-1}"
PIPELINE_REPLACE_SIMILARITY="${PIPELINE_REPLACE_SIMILARITY:-1}"
FRESH_START="${FRESH_START:-1}"
ATTEMPT_IDLE_TIMEOUT_SECONDS="${ATTEMPT_IDLE_TIMEOUT_SECONDS:-180}"

mkdir -p "$SCRIPT_DIR/logs"

cd "$REPO_ROOT"
docker compose --env-file "$DOCKER_ENV_FILE" -f "$DOCKER_COMPOSE_FILE" run --rm \
  -e SKIP_EMAIL_ALERTS="$SKIP_EMAIL_ALERTS" \
  -e PIPELINE_REPLACE_INPUT_SLICES="$PIPELINE_REPLACE_INPUT_SLICES" \
  -e PIPELINE_REPLACE_SIMILARITY="$PIPELINE_REPLACE_SIMILARITY" \
  -e FRESH_START="$FRESH_START" \
  -e ATTEMPT_IDLE_TIMEOUT_SECONDS="$ATTEMPT_IDLE_TIMEOUT_SECONDS" \
  current-season-job
