export const METRIC_LABELS = {
  "accelerations_per_90": "Accelerations /90",
  "accurate_crosses_percent": "Cross accuracy (%)",
  "accurate_forward_passes_percent": "Acc. forward passes (%)",
  "accurate_long_passes_percent": "Acc. long passes (%)",
  "accurate_passes_percent": "Passing accuracy (%)",
  "accurate_passes_to_final_third_percent": "Acc. to final third (%)",
  "accurate_passes_to_penalty_area_percent": "Acc. to penalty area (%)",
  "accurate_progressive_passes_percent": "Acc. progressive passes (%)",
  "accurate_smart_passes_percent": "Acc. smart passes (%)",
  "aerial_duels_gk_per_90": "GK aerials /90",
  "aerial_duels_per_90": "Aerial duels /90",
  "aerial_duels_won_percent": "Aerial duels won (%)",
  "assists_per_90": "Assists",
  "back_passes_to_gk_per_90": "Back passes to GK /90",
  "crosses_per_90": "Crosses /90",
  "deep_completions_per_90": "Deep completions /90",
  "deep_crosses_per_90": "Deep crosses /90",
  "def_duels_per_90": "Defensive duels /90",
  "def_duels_won_percent": "Defensive duels won (%)",
  "dribbles_per_90": "Dribbles /90",
  "exits_per_90": "Exits /90",
  "forward_passes_per_90": "Forward passes /90",
  "goal_conversion_rate": "Goal conversion (%)",
  "goals_conceded_per_90": "Goals conceded /90",
  "goals_per_90": "Goals",
  "goals_prevented_per_90": "Goals prevented /90",
  "interceptions_padj": "Interceptions (PAdj)",
  "interceptions_per_90": "Interceptions /90",
  "key_passes_per_90": "Key passes /90",
  "long_passes_per_90": "Long passes /90",
  "long_passes_received_per_90": "Long passes received /90",
  "offensive_duels_per_90": "Offensive duels /90",
  "passes_per_90": "Passes /90",
  "passes_received_per_90": "Passes received /90",
  "passes_to_final_third_per_90": "Passes to final third /90",
  "passes_to_penalty_area_per_90": "Passes to penalty area /90",
  "progressive_passes_per_90": "Progressive passes /90",
  "progressive_runs_per_90": "Progressive runs /90",
  "save_percent": "Save rate (%)",
  "shots_against_per_90": "Shots against /90",
  "shots_on_target_percent": "Shots on target (%)",
  "shots_per_90": "Shots /90",
  "sliding_tackles_per_90": "Sliding tackles /90",
  "smart_passes_per_90": "Smart passes /90",
  "successful_def_actions_per_90": "Def. actions successful /90",
  "successful_dribbles_percent": "Successful dribbles (%)",
  "touches_in_penalty_area_per_90": "Touches in box /90",
  "xa_per_90": "xA",
  "xg_against_per_90": "xGA /90",
  "xg_per_90": "xG"
};// eslint-disable-line
