const ROLE_LABELS = {
  "GK - Shot-stopper (mains)": "Shot-Stopping Goalkeeper",
  "GK - Relanceur (ball-playing)": "Ball-Playing Goalkeeper",
  "GK - Complet (sweeper-keeper)": "Sweeper Keeper",
  "DC - Stoppeur (agressif)": "Aggressive Centre Back",
  "DC - Relanceur (ball-playing CB)": "Ball-Playing Centre Back",
  "DC - Dominant aérien": "Aerial-Dominant Centre Back",
  "DC - Large gauche (wide LCB)": "Wide Left Centre Back",
  "DC - Large droit (wide RCB)": "Wide Right Centre Back",
  "Latéral gauche - Offensif complet": "Offensive Left Back",
  "Latéral droit - Offensif complet": "Offensive Right Back",
  "Latéral gauche - Solide défensivement": "Defensive Left Back",
  "Latéral droit - Solide défensivement": "Defensive Right Back",
  "Latéral gauche - Hybride (inversé)": "Inverted Left Back",
  "Latéral droit - Hybride (inversé)": "Inverted Right Back",
  "Piston gauche - Ligne haute": "High Left Wing Back",
  "Piston droit - Ligne haute": "High Right Wing Back",
  "Milieu défensif - Sentinelle": "Holding Midfielder",
  "Milieu défensif - Récupérateur": "Ball-Winning Midfielder",
  "6 - Destructeur (ball-winner)": "Ball-Winning Defensive Midfielder",
  "6 - Regista (deep-lying playmaker)": "Deep-Lying Playmaker",
  "Milieu relayeur - Box-to-box": "Box-to-Box Midfielder",
  "Milieu relayeur - Progression": "Progressive Midfielder",
  "8 gauche - Box-to-box": "Left Box-to-Box Midfielder",
  "8 droit - Box-to-box": "Right Box-to-Box Midfielder",
  "Mezzala gauche": "Left Mezzala",
  "Mezzala droit": "Right Mezzala",
  "Meneur reculé - Organisateur": "Deep-Lying Playmaker",
  "Milieu offensif - Créateur": "Creative Attacking Midfielder",
  "10 - Créateur (enganche/playmaker)": "Creative Number 10",
  "10 - Second attaquant (shadow striker)": "Shadow Striker",
  "Ailier gauche - Débordement": "Touchline Left Winger",
  "Ailier droit - Débordement": "Touchline Right Winger",
  "Ailier gauche - Intérieur": "Inside Left Winger",
  "Ailier droit - Intérieur": "Inside Right Winger",
  "Ailier gauche - Inversé": "Inside Left Winger",
  "Ailier droit - Inversé": "Inside Right Winger",
  "Ailier gauche - Deux voies": "Two-Way Left Winger",
  "Ailier droit - Deux voies": "Two-Way Right Winger",
  "Second attaquant / 10 - Créateur": "Creative Second Striker",
  "Avant-centre - Finisseur": "Finishing Striker",
  "Avant-centre - Point d'appui": "Target Striker",
  "Avant-centre - Pressing": "Pressing Striker",
  "Avant-centre - Complet": "Complete Striker",
  "9 - Pivot (target man)": "Target Striker",
  "9 - Renard (poacher)": "Poacher",
  "9 - Complet (complete forward)": "Complete Forward",
  "9 - Pressing (defensive forward)": "Pressing Forward",
  "9 - Décrocheur (DLF)": "Deep-Lying Forward",
};

export const englishRole = (role) => ROLE_LABELS[role] || role || "";

export const normalizeRoleForUse = (role) => englishRole(role).toLowerCase();
