# List of authorised users for NextLegend v2.

[[users]]
username = "yrachid"
display_name = "Yannis Rachid"
email = "yannis.rachid6@gmail.com"
password_hash = "917883352f8da82eb1dbc35bfc83ab3c622691c9e628b7b67a49c5b218ce6471"

[[users]]
username = "mrigoni"
display_name = "Matteo Rigoni"
email = "mrigoni.pro@gmail.com"
password_hash = "b2f9d1dc7b1c42314b1db1add90dba7a141c4bc17fc9fdf6a19cff8e5e97accf"

[[users]]
username = "ldiaz"
display_name = "Lidahi Diaz"
email = "lidahi.diaz@gmail.com"
password_hash = "1577fb45600f49da253b61e6a43402196c03f7efbda4597ceb9a65e0fdc4e637"

[[users]]
username = "nrachid"
display_name = "Nadir Rachid"
email = "nadir.rachid@gmail.com"
password_hash = "81f0c2395ab279a6daecb6cd69e3af33b1372f246adedd0e7947b837db8cfff5"
